# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c911c68ed83703de1cb96614f4c3164f4c3266b645d4d968023be0e961e2052adf7d8ecc79ed3529371be768ef1460a222edba411571b230e3af7562bef5488f

test:
  secret_key_base: db11b692fbf687ce4932f5074430af533d5d4150a37ad686d5d23b84531cdc9a4c215fb2faa15f68450483edf38cd0b822812cc76df9b7de6a1205e816e82e97

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
